---
time:
  begin: '2026-02-15T19:21:26+00:00'
  end: '2026-02-16T19:21:25+00:00'
data_log:
  total_time_steps: 12
  metrics_per_step: 2
  log_count: 24
synth_rate:
  cpu_instance: 3.6
  persistent_storage: 4.944
  total_rate: 8.544
