---
logs_dir_zuul: "/home/zuul/ci-framework-data/logs"
artifacts_dir_zuul: "/home/zuul/ci-framework-data/artifacts"

ck_synth_script: "{{ role_path }}/files/gen_synth_loki_data.py"
ck_data_template: "{{ role_path }}/template/loki_data_templ.j2"
ck_data_config: "{{ role_path }}/files/test_static.yml"
ck_output_file_local: "{{ artifacts_dir_zuul }}/loki_synth_data.json"
ck_output_file_remote: "{{ logs_dir_zuul }}/gen_loki_synth_data.log"
ck_loki_retrieve_file: "{{ logs_dir_zuul }}/retrieve_loki_op.json"

# loki url's
loki_base_url: "https://cloudkitty-lokistack-openstack.apps-crc.testing"
loki_push_url: "{{ loki_base_url }}/api/logs/v1/cloudkitty/loki/api/v1/push"
loki_query_url: "{{ loki_base_url }}/api/logs/v1/cloudkitty/loki/api/v1/query_range"

# Ingester URL
ingester_flush_url: "https://cloudkitty-lokistack-ingester-http.openstack.svc:3100/flush"

# Cloudkitty certificates
cert_secret_name: "cert-cloudkitty-client-internal"
cert_dir: "{{ ansible_user_dir }}/ck-certs"

client_secret: "secret/cloudkitty-lokistack-gateway-client-http"
ca_configmap: "cm/cloudkitty-lokistack-ca-bundle"
local_cert_dir: "{{ ansible_env.HOME }}/flush_certs"
remote_cert_dir: "osp-certs"

# LogQL Query
logql_query: "{{ loki_query | default('{service=\"cloudkitty\"}') }}"

# Time window settings
lookback_days: "{{ lookback | default(6) }}"
limit_logs: "{{ limit | default(50) }}"

# vars
namespace: "openstack"
openstackpod: "openstackclient"