---
# logs_dir_zuul: "/home/zuul/ci-framework-data/logs"
# artifacts_dir_zuul: "/home/zuul/ci-framework-data/artifacts"
logs_dir_zuul: "{{ ansible_env.HOME }}/ci-framework-data/logs"
artifacts_dir_zuul: "{{ ansible_env.HOME }}/ci-framework-data/artifacts"

ck_scenario_dir: "{{ role_path }}/files"
ck_synth_data_suffix: "-synth_data.json"
ck_loki_data_suffix: "-loki_data.json"
ck_synth_totals_suffix: "-totals_synth.yml"
ck_loki_totals_suffix: "-totals_loki.yml"
ck_begin_end_suffix: "-begin_end.yml"

ck_synth_script: "{{ role_path }}/files/gen_synth_loki_data.py"
ck_data_template: "{{ role_path }}/templates/loki_data_templ.j2"
ck_totals_script: "{{ role_path }}/files/gen_synth_loki_metrics.totals.py"

### from Muneesah
# Cloudkitty certificates
cert_secret_name: "cert-cloudkitty-client-internal"
cert_dir: "{{ ansible_user_dir }}/ck-certs"

client_secret: "secret/cloudkitty-lokistack-gateway-client-http"
ca_configmap: "cm/cloudkitty-lokistack-ca-bundle"
remote_cert_dir: "osp-certs"
local_cert_dir: "{{ ansible_env.HOME }}/ci-framework-data/flush_certs"

# LogQL Query
logql_query: "{{ loki_query | default('{service=\"cloudkitty\"}') }}"

# vars
ck_namespace: "openstack"
openstackpod: "openstackclient"

# Time window settings
lookback: 6
limit: 50
