---
logs_dir: "/home/zuul/ci-framework-data/logs"
output_file_remote: "{{ logs_dir_zuul }}/gen_loki_synth_data.log"

ck_synth_script: "{{ role_path }}/files/gen_synth_loki_data.py"
ck_data_template: "{{ role_path }}/template/loki_data_templ.j2"
ck_data_config: "{{ role_path }}/files/test_static.yml"
ck_output_file_local: "{{ role_path }}/files/loki_synth_data.json"
ck_output_file_remote: "{{ logs_dir_zuul }}/gen_loki_synth_data.log"
