---
galaxy_info:
  author: CloudOps
  description: "Tests for the HighAvailability functionality deployed in STF"
  company: Red Hat

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: "Apache-2.0"

  min_ansible_version: "2.1"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags: []

dependencies: []
