---
openstack_cmd: "openstack"

# Cloudkitty certificates
gateway_client_cert_secret_name: "cert-cloudkitty-client-internal"
gateway_client_cert_dir: "{{ ansible_user_dir }}/ck-certs"

ingester_client_cert_secret: "secret/cloudkitty-lokistack-gateway-client-http"
ingester_ca_configmap: "cm/cloudkitty-lokistack-ca-bundle"
ingester_client_cert_dir: "{{ ansible_user_dir }}/flush_certs"
osp_remote_cert_dir: "osp-certs"

# Loki Ingest & Retrieve logs
ck_output_file_remote: "{{ logs_dir }}/gen_loki_synth_data.log"
ck_loki_retrieve_file: "{{ logs_dir }}/retrieve_loki_op.json"

# LogQL Query
logql_query: "{{ loki_query | default('{service=\"cloudkitty\"}') }}"

# vars
openstack_ns: "openstack"
openstackpod: "openstackclient"

# Time window settings
lookback: 6
