---
openstack_cmd: "openstack"

# Cloudkitty certificates
cert_secret_name: "cert-cloudkitty-client-internal"
cert_dir: "{{ ansible_user_dir }}/ck-certs"

client_secret: "secret/cloudkitty-lokistack-gateway-client-http"
ca_configmap: "cm/cloudkitty-lokistack-ca-bundle"
remote_cert_dir: "osp-certs"
local_cert_dir: "{{ ansible_env.HOME }}/flush_certs"


# Loki Ingest & Retrieve logs
logs_dir_zuul: "/home/zuul/ci-framework-data/logs"
ck_output_file_remote: "{{ logs_dir_zuul }}/gen_loki_synth_data.log"
ck_loki_retrieve_file: "{{ logs_dir_zuul }}/retrieve_loki_op.json"

# LogQL Query
logql_query: "{{ loki_query | default('{service=\"cloudkitty\"}') }}"

# vars
namespace: "openstack"
openstackpod: "openstackclient"

# Time window settings
lookback: 6
limit: 50