---
- name: Verify CRD "{{ item }}"
  ansible.builtin.shell:
    cmd: |
      oc get crd "{{ item }}"
  changed_when: false
  register: output

- name: |
    TEST Verify CRD {{ item }} is found
  ansible.builtin.assert:
    that:
      - "'NotFound' not in output.stderr"
    success_msg: "CRD {{ item }} is found."
    fail_msg: "CRD {{ item }} not found. Error: {{ output.stderr }}"
