---
galaxy_info:
  author: Alex Yefimov
  description: Tests the chargeback feature is set up in OpenStack running on OpenShift
  company: Red Hat

  license: Apache-2.0

  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
