name: Check custom_logger
on: [push, pull_request]

jobs:
  test_custom_logger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install ansible
      - name: Run the test_logger playbook.
        run: cd /tmp && rm -rf test_run_result.out && ${HOME}/.local/bin/ansible-playbook -v github/test_logger.yml && diff -s test_run_result.out github/test_logger_expected

